## Enunciado

<div style="text-align: justify">Lance dos dados y calcule la probabilidad P(la suma de puntos sea ≥ 9 | la cara 6
aparece).
</div>

In [22]:
from numpy.random import choice
from collections import Counter
from icecream import ic
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import plotly.express as px

## Simulación lanzamiento de dos dados

In [28]:
resultados = [1,2,3,4,5,6]
tamano_muestra = 100000

# Resultados lanzamiento de dado 1
dado_1 = choice(resultados, tamano_muestra)
print(dado_1)
# Resultados lanzamiendo de dado 2
dado_2 = choice(resultados, tamano_muestra)
print(dado_2)
# Suma de los resultados dado 1 + dado 2
suma_result = dado_1 + dado_2
print(suma_result) 



[1 3 5 ... 3 4 2]
[6 2 1 ... 1 1 3]
[7 5 6 ... 4 5 5]


In [24]:

dado_1 = pd.Series(dado_1) 
dado_1
dado_2 = pd.Series(dado_2)
dado_2
suma_result = pd.Series(suma_result) 
suma_result
dado_1_6 = dado_1 == 6 
print(dado_1_6.to_numpy()) 
dado_2_6 = dado_2 == 6
print(dado_2_6.to_numpy())
suma_result_6 = suma_result[dado_1_6 | dado_2_6] 
print(suma_result_6)

[False False  True ... False False  True]
[False False False ... False False False]
2        10
6        11
7        10
9         7
17        9
         ..
99985    11
99988     7
99991    11
99995     8
99999     8
Length: 30411, dtype: int32


In [25]:
# Contando número de ejecuciones donde salió al menos un seis
conteo_ejecuciones_con_6 = suma_result_6.count()
print(conteo_ejecuciones_con_6)

# Contando ejecuciones con suma mayor o igual a 9
conteo_suma_mayoroigual_9 = suma_result_6[suma_result_6>=9].count()
print(conteo_suma_mayoroigual_9)


30411
19363


## Probabilidad P(la suma de puntos sea ≥ 9 | la cara 6 aparece)

In [26]:
probabilidad = conteo_suma_mayoroigual_9 / conteo_ejecuciones_con_6  #probbailidad analítica = 0.6363
print('P(la suma de puntos sea ≥ 9 | la cara 6 aparece) = ', probabilidad)

P(la suma de puntos sea ≥ 9 | la cara 6 aparece) =  0.6367104008418006


In [27]:

df = pd.DataFrame({
    'Dado_1': dado_1,
    'Dado_2': dado_2,
    'Suma_Result': suma_result
})


df_6 = df[(df['Dado_1'] == 6) | (df['Dado_2'] == 6)]


conteo_ejecuciones_con_6 = len(df_6)


conteo_suma_mayoroigual_9 = len(df_6[df_6['Suma_Result'] >= 9])


probabilidad = conteo_suma_mayoroigual_9 / conteo_ejecuciones_con_6

fig = px.pie(names=['Suma ≥ 9', 'Suma < 9'],
             values=[conteo_suma_mayoroigual_9, conteo_ejecuciones_con_6 - conteo_suma_mayoroigual_9],
             title=f'Probabilidad P(Suma ≥ 9 | Al menos un 6) = {probabilidad:.4f}',
             labels={'label': 'Suma de Resultados'},
             color_discrete_sequence=['darkblue', 'royalblue'])


fig.show()
   